import os
import json
import urllib.request
from typing import Tuple, Dict, Any
from agent.mcp_server import MCPServer


class CognitiveAgent:
    """
    Autonomous AI Cognitive Engine for Smart Building Closed-Loop Optimization.
    Pairs physics-based EnergyPlus simulation with a self-hosted Open-Source LLM
    (Llama 3.1 / Qwen 2.5 / Mistral) and Model Context Protocol (MCP) server.
    """

    def __init__(self, actuator_manager=None, llm_endpoint: str = "http://127.0.0.1:11434/v1/chat/completions"):
        self.mcp_server = MCPServer(actuator_manager=actuator_manager)
        self.llm_endpoint = llm_endpoint
        self.model_name = "llama3.1:8b-instruct"
        self.llm_available = None

    def check_llm_connection(self) -> bool:
        """Fast check to verify if LLM endpoint is online without delaying physics timesteps."""
        if self.llm_available is not None:
            return self.llm_available
        try:
            req = urllib.request.Request("http://127.0.0.1:11434/api/tags", method="GET")
            with urllib.request.urlopen(req, timeout=0.1) as res:
                if res.status == 200:
                    self.llm_available = True
                    return True
        except Exception:
            pass
        self.llm_available = False
        return False

    def query_oss_llm(self, telemetry: Dict[str, Any]) -> Tuple[float, float, str]:
        """
        Query the self-hosted Open-Source LLM endpoint with building telemetry and MCP tools.
        Returns target (cooling_setpoint, heating_setpoint, reasoning).
        """
        if self.check_llm_connection():
            payload = {
                "model": self.model_name,
                "messages": [
                    {
                        "role": "system",
                        "content": "You are the EcoLoop Autonomous Smart Building Cognitive Agent. Your goal is to optimize building energy consumption while enforcing ASHRAE 55 thermal comfort (-0.5 <= PMV <= +0.5). Use the provided MCP tools to evaluate Energy Conservation Measures (ECMs) and adjust setpoints.",
                    },
                    {
                        "role": "user",
                        "content": f"Current Building Telemetry: {json.dumps(telemetry)}",
                    },
                ],
                "tools": self.mcp_server.get_tool_definitions(),
            }

            try:
                req = urllib.request.Request(
                    self.llm_endpoint,
                    data=json.dumps(payload).encode("utf-8"),
                    headers={"Content-Type": "application/json"},
                    method="POST",
                )
                with urllib.request.urlopen(req, timeout=0.5) as response:
                    res_data = json.loads(response.read().decode("utf-8"))
                    choices = res_data.get("choices", [])
                    if choices:
                        msg = choices[0].get("message", {})
                        tool_calls = msg.get("tool_calls", [])
                        if tool_calls:
                            # Extract tool call generated by OSS LLM
                            fn = tool_calls[0].get("function", {})
                            fn_args = json.loads(fn.get("arguments", "{}"))
                            
                            # Execute tool call via MCP Server
                            ecm_result = self.mcp_server.execute_tool("evaluate_ecm", fn_args)
                            return (
                                ecm_result.get("recommended_cooling_sp", 24.5),
                                ecm_result.get("recommended_heating_sp", 20.5),
                                f"[{self.model_name} OSS LLM] {ecm_result.get('reasoning')}",
                            )
            except Exception:
                self.llm_available = False

        # Direct MCP reasoning fallback
        hour = telemetry.get("hour", 12)
        occ = telemetry.get("total_occupancy", 0.0)
        pmv = telemetry.get("avg_pmv", 0.0)

        ecm_result = self.mcp_server.execute_tool("evaluate_ecm", {"hour": hour, "occupancy": occ, "pmv": pmv})
        return (
            ecm_result.get("recommended_cooling_sp", 24.5),
            ecm_result.get("recommended_heating_sp", 20.5),
            f"[Autonomous MCP Engine] {ecm_result.get('reasoning')}",
        )

    def evaluate_timestep(self, ep_state, bld_state) -> Tuple[float, float, str]:
        """
        Closed-loop agent execution step:
        1. Query building telemetry status from MCP Server.
        2. Send telemetry to self-hosted OSS LLM and execute MCP tools.
        3. Inject target setpoint overrides directly back into EnergyPlus via actuators.
        """
        status = self.mcp_server.execute_tool("get_building_status", {}, state=bld_state)
        telemetry = status.get("telemetry", {})
        telemetry["hour"] = bld_state.hour
        telemetry["total_occupancy"] = bld_state.total_occupancy
        telemetry["avg_pmv"] = bld_state.avg_pmv

        # Query OSS LLM & MCP tool execution
        target_clg, target_htg, reasoning = self.query_oss_llm(telemetry)

        # Apply setpoints via MCP tool with PyEnergyPlus C state pointer
        adjust_result = self.mcp_server.execute_tool(
            "adjust_thermostat_setpoints",
            {
                "cooling_setpoint": target_clg,
                "heating_setpoint": target_htg,
                "reasoning": reasoning,
            },
            state=ep_state,
        )

        applied_clg = adjust_result.get("applied_cooling_setpoint", target_clg)
        applied_htg = adjust_result.get("applied_heating_setpoint", target_htg)

        return applied_clg, applied_htg, reasoning

    def parse_idf_model(self, idf_name: str = "5ZoneAirCooled.idf") -> Dict[str, Any]:
        """Parse IDF building model via MCP Server tools."""
        return self.mcp_server.execute_tool("parse_idf_file", {"idf_name": idf_name})

    def diagnose_runtime_errors(self, log_filename: str = "eplusout.err") -> Dict[str, Any]:
        """Extract and analyze simulation runtime errors via MCP Server tools."""
        return self.mcp_server.execute_tool("extract_runtime_errors", {"log_filename": log_filename})

    def execute_task(self, task_name: str = "Comparative", idf_name: str = "5ZoneAirCooled.idf") -> Dict[str, Any]:
        """Execute autonomous simulation task via MCP Server tools."""
        return self.mcp_server.execute_tool("execute_simulation_task", {"mode": task_name, "idf_name": idf_name})

